package com.demo.convertor.constants;

public enum BerlinClockMinutesRange {
	
	LESS_THAN_5("OOOOOOOOOOO"), 
	MORE_THAN_5_BUT_LESS_THAN_10("YOOOOOOOOOO"), 
	MORE_THAN_10_BUT_LESS_THAN_15("YYOOOOOOOOO"), 
	MORE_THAN_15_BUT_LESS_THAN_20("YYROOOOOOOO"), 
	MORE_THAN_20_BUT_LESS_THAN_25("YYRY0OOOOOO"), 
	MORE_THAN_25_BUT_LESS_THAN_30("YYRYY0OOOOO"), 
	MORE_THAN_30_BUT_LESS_THAN_35("YYRYYROOOOO"), 
	MORE_THAN_35_BUT_LESS_THAN_40("YYRYYRYOOOO"), 
	MORE_THAN_40_BUT_LESS_THAN_45("YYRYYRYYOOO"), 
	MORE_THAN_45_BUT_LESS_THAN_50("YYRYYRYYROO"), 
	MORE_THAN_50_BUT_LESS_THAN_55("YYRYYRYYRYO"), 
	MORE_THAN_55("YYRYYRYYRYY"),
	ADD_ZERO_MINUTES("OOOO"), 
	ADD_ONE_MINUTE("YOOO"), 
	ADD_TWO_MINUTES("YYOO"), 
	ADD_THREE_MINUTES("YYYO"), 
	ADD_FOUR_MINUTES("YYYY");

	private String value;

	private BerlinClockMinutesRange(String value) {
		this.value = value;
	}

	public String getValue() {
		return value;
	}

}
